# Generated by Django 5.1.15 on 2026-09-03 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Должность"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("image", models.ImageField(upload_to="about/", verbose_name="Фото")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_ceo",
                    models.BooleanField(
                        default=False, verbose_name="Генеральный директор"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CarouselSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подзаголовок"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="carousel/", verbose_name="Изображение"
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="Ссылка")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Слайд карусели",
                "verbose_name_plural": "Слайды карусели",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Наша философия",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                ("text", models.TextField(verbose_name="Описание ценностей")),
                (
                    "background",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about/bg/",
                        verbose_name="Фон (опционально)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о компании",
                "verbose_name_plural": "Информация о компании",
            },
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата отправки"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Заголовок записи"),
                ),
                ("description", models.TextField(verbose_name="Текст записи")),
                ("author", models.CharField(max_length=100, verbose_name="Имя автора")),
                ("date", models.DateField(verbose_name="Дата публикации")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Заголовок записи"),
                ),
                ("description", models.TextField(verbose_name="Текст записи")),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/", verbose_name="Изображение"
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="Ссылка")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата реализации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка проекта",
                "verbose_name_plural": "Карточки проектов",
                "ordering": ["-date"],
            },
        ),
    ]
